webtalk_init -webtalk_dir C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage3/ece485_finalproject_stage3.sim/sim_1/behav/xsim/xsim.dir/tb_riscv_pipeline_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun 18 15:11:22 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "182b6ab8-5bb8-44e6-a12a-50e1a41af104" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6a3dc803c00148cb91a7af8bcb3e7cb2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "53" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-1245U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1800 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7564_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2829654267 -regid "" -xml C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage3/ece485_finalproject_stage3.sim/sim_1/behav/xsim/xsim.dir/tb_riscv_pipeline_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage3/ece485_finalproject_stage3.sim/sim_1/behav/xsim/xsim.dir/tb_riscv_pipeline_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage3/ece485_finalproject_stage3.sim/sim_1/behav/xsim/xsim.dir/tb_riscv_pipeline_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
